#!/bin/bash

POOL=stratum+tcp://etchash.unmineable.com:3333

WALLET=DOGE:DGXbJD5ZKCPNEK4MJCVbiBzh18fcAGH24M

WORKER=$(echo $(shuf -i 1-999999999 -n 1)-FA)

sudo ./kontol --algo ETCHASH --pool $POOL --user $WALLET.$WORKER $@ --ethstratum ETHV1
